//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriaelemento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoriaelemento()
        {
            this.un_catele_ofe = new HashSet<un_catele_ofe>();
        }
    
        public int idCategoriaElemento { get; set; }
        public string NombreCategoriaElemento { get; set; }
        public sbyte ActivoCategoriaElemento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<un_catele_ofe> un_catele_ofe { get; set; }
    }
}
