//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kukulkanEntities : DbContext
    {
        public kukulkanEntities()
            : base("name=kukulkanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_estadosol> cat_estadosol { get; set; }
        public virtual DbSet<categoriaelemento> categoriaelemento { get; set; }
        public virtual DbSet<estadouser> estadouser { get; set; }
        public virtual DbSet<images_ofertas> images_ofertas { get; set; }
        public virtual DbSet<images_solicitud> images_solicitud { get; set; }
        public virtual DbSet<ofertas> ofertas { get; set; }
        public virtual DbSet<solicitudes> solicitudes { get; set; }
        public virtual DbSet<tiposusuario> tiposusuario { get; set; }
        public virtual DbSet<un_catele_ofe> un_catele_ofe { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<tipoplanta_solicitud> tipoplanta_solicitud { get; set; }
        public virtual DbSet<tipoplantas> tipoplantas { get; set; }
        public virtual DbSet<solicitud_cotizacion> solicitud_cotizacion { get; set; }
    }
}
