//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int idSolicitud { get; set; }
        public string TituloSolicitud { get; set; }
        public int EstadoSolicitud { get; set; }
        public string DescripcionSolicitud { get; set; }
        public byte[] ImagenSolicitud { get; set; }
        public int idUsuario { get; set; }
    
        public virtual cat_estadosol cat_estadosol { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
