//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud_cotizacion
    {
        public int idSolicitud_Cotizacion { get; set; }
        public string Comentarios_cotizacion { get; set; }
        public Nullable<float> Costo_Cotizacion { get; set; }
        public int IdSolicitud { get; set; }
        public int IdUsuarioCotiza { get; set; }
    
        public virtual solicitudes solicitudes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
