//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoplanta_solicitud
    {
        public int IdTipoPlanta_Solicitud { get; set; }
        public Nullable<int> IdtipoPlanta { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
    
        public virtual solicitudes solicitudes { get; set; }
        public virtual tipoplantas tipoplantas { get; set; }
    }
}
