//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoplantas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipoplantas()
        {
            this.tipoplanta_solicitud = new HashSet<tipoplanta_solicitud>();
        }
    
        public int idTipoPlantas { get; set; }
        public string DescripcionTipoPlantas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipoplanta_solicitud> tipoplanta_solicitud { get; set; }
    }
}
