//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumKaax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_catele_ofe
    {
        public int idun_catele_ofecol { get; set; }
        public int idUn_CatEl { get; set; }
        public int idUn_Ofe { get; set; }
    
        public virtual categoriaelemento categoriaelemento { get; set; }
        public virtual ofertas ofertas { get; set; }
    }
}
